name: "deploy"

on:
  push:
    branches:
      - bundled-tea-cli

jobs:
  build_desktop:
    strategy:
      matrix:
        platform:
          # X86+64 is built with ARM64 also
          - darwin+aarch64
    uses: ./.github/workflows/build-sign-notarize.yml
    with:
      platform: ${{ matrix.platform }}
      s3-prefix: bundle-test
      debug: 0
    secrets: inherit
