on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_desktop:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: teaxyz/setup@v0
    - name: build
      run: tea -ES xc dist
      env:
        USE_HARD_LINKS: false
    - name: Compress action step
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: modules/cli/
        files: ./
        outPath: release.tar.gz
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz"
        bodyFile: "README.md"

