name: "test"

on:
  push:
    branches:
      - test-again

jobs:
  changes:
    runs-on: macos-latest
    steps:
    - name: create x86 dmg
      run: |
        sh <(curl https://tea.xyz) --yes
        sh <(curl https://tea.xyz) +github.com/create-dmg/create-dmg
        test -d "$HOME/.tea" && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash --silent)