name: "test"

on:
  push:
    branches:
      - test-again

jobs:
  changes:
    runs-on: macos-latest
    steps:
    - uses: teaxyz/setup@v0
    - uses: actions/checkout@v3
    - name: create x86 dmg
      run: |
        tea +github.com/create-dmg/create-dmg
        tea -SE create-dmg --version
